runtime: python39
entrypoint: gunicorn -b :$PORT main:app

instance_class: F2
env_variables:
  CLOUD_STORAGE_BUCKET: "cloud-final"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  cool_down_period_sec: 60
